### ISSUE TITLE
Occasional errors occur

### ISSUE THREAD

**Issue by condorheroblog** [condorheroblog/merge-pdfs#2]
```bash
PythonError: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 48, in _get_pypi_json
    metadata = await fetch_string(url, fetch_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/_compat_in_pyodide.py", line 34, in fetch_string
    return await (await pyfetch(url, **kwargs)).string()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/pyodide/http.py", line 254, in pyfetch
    raise OSError(e.message) from None
OSError: fetch failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 576, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 342, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 349, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 441, in add_requirement_inner
    metadata = await _get_pypi_json(req.name, self.fetch_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 50, in _get_pypi_json
    raise ValueError(
ValueError: Can't fetch metadata for 'pypdf' from PyPI. Please make sure you have entered a correct package name.
```

**Comment by condorheroblog** [comment]
Generally, it occurs when the command is run for the first time after npm install, and it is fine to run the command for the second time after encountering an error.

**Comment by condorheroblog** [comment]
The [v0.0.4](https://github.com/condorheroblog/merge-pdfs/releases/tag/v0.0.4) version has been changed to local loading, It's not a matter.
